# Generated by Django 3.0 on 2021-01-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart_stemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cartquan',
            field=models.IntegerField(default=0),
        ),
    ]
