# Generated by Django 3.0 on 2021-02-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210205_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='silptime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderpending',
            name='silp',
            field=models.ImageField(blank=True, null=True, upload_to='silp'),
        ),
    ]
