# Generated by Django 3.0 on 2021-02-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
