# Generated by Django 3.0 on 2021-02-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20210221_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='/default.jpg', null=True, upload_to='photoprofile'),
        ),
    ]
